name: Generate changelog PR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate the full changelog
        uses: orhun/git-cliff-action@v4
        id: git_cliff_full
        with:
          config: cliff.toml
          args: --verbose --bump
        env:
          OUTPUT: CHANGELOG.md

      - name: Generate latest changes
        uses: orhun/git-cliff-action@v4
        id: git_cliff_latest
        with:
          config: cliff.toml
          args: --verbose --latest --bump --unreleased

      - name: Create Pull Request
        if: steps.git_cliff_full.outputs.version != 'null'
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            CHANGELOG.md
          base: main
          commit-message: "üìù(release) update CHANGELOG.md for ${{ steps.git_cliff_full.outputs.version }}"
          signoff: true
          sign-commits: true
          branch: chore/next-release-changelog
          delete-branch: true
          title: "üìù(release): ${{ steps.git_cliff_full.outputs.version }}"
          body: ${{ steps.git_cliff_latest.outputs.content }}
          labels: |
            pending-release
