name: Label Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  merge_group:

jobs:
  require-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Verify changelog label
        uses: mheap/github-action-required-labels@v5.5
        with:
          mode: exactly
          count: 1
          labels: |
            breaking
            added
            modified
            removed
            bugfix
            dependencies
            documentation
